from __future__ import annotations

import tarfile
import zipfile
from pathlib import Path

import pytest


REPO_ROOT = Path(__file__).resolve().parents[1]
DIST_DIR = REPO_ROOT / "dist"



def test_build_artifacts_include_runtime_schema_files():
    wheel_files = sorted(DIST_DIR.glob("*.whl"))
    sdist_files = sorted(DIST_DIR.glob("*.tar.gz"))

    if not wheel_files or not sdist_files:
        pytest.skip("dist artifacts are generated by the build job before this check")

    with zipfile.ZipFile(wheel_files[-1]) as zf:
        names = set(zf.namelist())
        assert "wangchuan/v3/schema.sql" in names
        assert "wangchuan/v3/.env.example" in names

    with tarfile.open(sdist_files[-1]) as tf:
        names = set(tf.getnames())
        prefix = sdist_files[-1].name[:-7]
        assert f"{prefix}/src/wangchuan/v3/schema.sql" in names
        assert f"{prefix}/src/wangchuan/v3/.env.example" in names
